cargo-features = ["profile-rustflags"]

[package]
name = "pchan"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
    "experimental/pchan-dbg-gpui",
    "experimental/pchan-mini",
    "pchan-audio",
    "pchan-bind",
    "pchan-emu",
    "pchan-executor",
    "pchan-gpu",
    "pchan-input",
    "pchan-macros",
    "pchan-steel",
    "pchan-utils",
]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
std_instead_of_core = "deny"
std_instead_of_alloc = "deny"

# bad lints
unreadable_literal = "allow"
match_bool = "allow"
too_many_lines = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"
single_match_else = "allow"
type_complexity = "allow"
needless_pass_by_value = "allow"
similar_names = "allow"
wildcard_imports = "allow"
redundant_closure_for_method_calls = "allow"
ignored_unit_patterns = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
unused_self = "allow"

# causes problems with dynasm
semicolon_if_nothing_returned = "allow"
used_underscore_binding = "allow"
unnecessary_semicolon = "allow"
cast_sign_loss = "allow"
cast_possible_wrap = "allow"

[workspace.dependencies]
arbitrary-int = "2.2.0"
bitbybit = "2.0.1"
const-hex = { version = "1.19.3", features = ["nightly", "portable-simd"] }
kanal = "0.1.1"
pchan-audio = { path = "./pchan-audio" }
pchan-bind = { path = "./pchan-bind" }
pchan-emu = { path = "./pchan-emu" }
pchan-executor = { path = "./pchan-executor" }
pchan-gpu = { path = "./pchan-gpu" }
pchan-macros = { path = "./pchan-macros" }
pchan-utils = { path = "./pchan-utils", default-features = false }
smol = "2.0.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[lints]
workspace = true

[profile.dev]
opt-level = "s"
panic = "unwind"

[profile.dev.package."*"]
opt-level = "s"

[profile.release]
lto = "thin"
panic = "unwind"

[profile.bench]
debug = 2

[profile.san]
inherits = "dev"
opt-level = 1
debug = true
overflow-checks = true
panic = "abort"
rustflags = ["-Zsanitizer=address"]
