[package]
name = "pchan-emu"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
fetch-channel = []
amidog-tests = []
debugger-ext = []
trace = []
std = []

[dependencies]
arbitrary-int.workspace = true
bitbybit.workspace = true
bitvec = "1.1.1"
byteorder = "1.5.0"
derive_more = { version = "2.1.1", features = ["add", "debug", "deref", "display", "full"] }
dynasm = "5.1.0"
dynasmrt = "5.1.0"
enum_dispatch = "0.3.13"
glam = "0.34.1"
heapless = "0.9.3"
kanal.workspace = true
pchan-bind.workspace = true
pchan-macros = { workspace = true }
pchan-utils = { workspace = true, features = ["tracy"] }
slotmap = "1.1.1"
smallbox = { version = "0.8.8", features = ["nightly"] }
smallvec = { version = "1.16.2", features = ["const_new"] }
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.21"
tracing = { workspace = true }

[dev-dependencies]
assert_hex = "0.4.1"
color-eyre = "*" 
criterion = { version = "0.8", features = ["html_reports"] }
pchan-utils = { workspace = true, features = ["tracing-subscriber"] }
pretty_assertions = { version = "1.4.1", features = ["unstable"] }
rstest = "*"

[lints]
workspace = true

[[bench]]
name = "bench_dynarec_v2"
harness = false
