[package]
name = "pchan-mini"
version = "0.1.0"
edition = "2024"

[dependencies]
fltk = { version = "1.5.23", features = ["rwh06"] }
kanal.workspace = true
miette = "7.6.0"
pchan-audio.workspace = true
pchan-bind.workspace = true
pchan-emu = { workspace = true, features = ["debugger-ext"] }
pchan-gpu.workspace = true
pchan-steel = { version = "0.1.0", path = "../../pchan-steel" }
pchan-utils = { workspace = true, features = ["tracing-subscriber"] }
smol.workspace = true

[lints]
workspace = true
