[package]
name = "pchan-mini"
version = "0.1.0"
edition = "2024"

[dependencies]
fltk = { version = "1.5.23", features = ["raw-window-handle"] }
kanal.workspace = true
miette = "7.6.0"
pchan-audio.workspace = true
pchan-bind.workspace = true
pchan-emu = { workspace = true, features = ["debugger-ext"] }
pchan-gpu.workspace = true
pchan-utils.workspace = true
smol.workspace = true

[lints]
workspace = true
