[package]
name = "pchan-steel"
version = "0.1.0"
edition = "2024"

[features]
default = ["repl", "ctrlc"]
repl = ["dep:steel-repl"]
ctrlc = ["dep:ctrlc"]

[dependencies]
ctrlc = { version = "3.5.2", optional = true }
derive_more = { version = "2.1.1", features = ["debug"] }
kanal.workspace = true
miette = "7.6.0"
pchan-bind.workspace = true
pchan-emu = { workspace = true, features = ["debugger-ext"] }
pchan-utils = { workspace = true, default-features = false }
smol.workspace = true
steel-core = { git = "https://github.com/wyvernbw/steel.git", branch = "wyvernbw/opt-jit", version = "0.8.3" }
steel-derive = { git = "https://github.com/wyvernbw/steel.git", branch = "wyvernbw/opt-jit", version = "0.8.3" }
steel-repl = { git = "https://github.com/wyvernbw/steel.git", branch = "wyvernbw/opt-jit", version = "0.8.3", optional = true }
thiserror = "2.0.21"

[lints]
workspace = true
