[package]
name = "pchan-steel"
version = "0.1.0"
edition = "2024"

[features]
default = ["repl"]
repl = ["dep:steel-repl"]

[dependencies]
kanal.workspace = true
pchan-bind.workspace = true
pchan-emu = { workspace = true, features = ["debugger-ext"] }
pchan-utils = { workspace = true, default-features = false }
smol.workspace = true
steel-core = { git = "https://github.com/wyvernbw/steel.git", branch="wyvernbw/opt-jit", version = "0.8.3" }
steel-repl = { git = "https://github.com/wyvernbw/steel.git", branch="wyvernbw/opt-jit", version = "0.8.3", optional = true }
steel-derive = { git = "https://github.com/wyvernbw/steel.git", branch="wyvernbw/opt-jit", version = "0.8.3" }
thiserror = "2.0.21"
derive_more = { version = "2.1.1", features = ["debug"] }

[lints]
workspace = true
