[package]
name = "pchan-gpu"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
wgpu = "30.0.1"
thiserror = "2.0.21"
pchan-emu = {workspace = true}
pchan-macros = { workspace = true }
pchan-utils = { workspace = true, features = ["tracy"] }
tracing = { workspace = true }
glam = "0.33.9"
pchan-executor.workspace = true
kanal.workspace = true
heapless = "0.9.3"
bitbybit.workspace = true
arbitrary-int.workspace = true
smol.workspace = true

[dev-dependencies]
pretty_assertions = {version = "1.4.1", features = ["unstable"]}
rstest = "*"
color-eyre = "*" 
criterion = { version = "0.8", features = ["html_reports"] }
bitbybit.workspace = true
arbitrary-int.workspace = true
