[package]
name = "pchan-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
arbitrary-int.workspace = true
bitbybit.workspace = true
glam = "0.34.1"
heapless = "0.9.3"
kanal.workspace = true
pchan-emu = { workspace = true }
pchan-executor.workspace = true
pchan-macros = { workspace = true }
pchan-utils = { workspace = true, features = ["tracy"] }
smol.workspace = true
thiserror = "2.0.21"
tracing = { workspace = true }
wgpu = "30.0.1"

[dev-dependencies]
arbitrary-int.workspace = true
bitbybit.workspace = true
color-eyre = "*" 
criterion = { version = "0.8", features = ["html_reports"] }
pretty_assertions = { version = "1.4.1", features = ["unstable"] }
rstest = "*"

[lints]
workspace = true
