[package]
name = "pchan-dbg-gpui"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
dhat-heap = ["dep:dhat"]    

[dependencies]
gpui = { package = "gpui-ce", version = "0.2.2" }
gpui_platform = { package = "gpui_ce_platform", version = "0.1.0", features = ["font-kit"] }
gpui-component = { package = "gpui_ce_components", version = "0.2.0" }
gpui-base = { package = "gpui_ce_components_base", version = "0.2.0" }
gpui-kit-assets = { package = "gpui_ce_components_assets", version = "0.2.0" }
pchan-emu = { workspace = true, features = ["debugger-ext"] }
pchan-gpu.workspace = true
miette = "7.6.0"
kanal.workspace = true
pchan-utils = { workspace = true, features = ["tracing-subscriber"] }
pchan-audio.workspace = true
pchan-bind.workspace = true
image = { version = "0.25.10", default-features = false }
dhat = { version = "*", optional = true }
objc2-metal = { version = "0.3.2", features = ["objc2-io-surface"] }
core-video = { version = "0.5.2", features = ["metal"] }
core-foundation = "0.10.0"
objc2-io-surface = "0.3.2"
objc2-core-foundation = "0.3.2"
event-listener = "5.4.2"
futures-lite = "2.6.1"
bumpalo = { version = "3.20.3", features = ["allocator_api"] }
